### PR TITLE
i18n pluralization

### PR DESCRIPTION
**Pull request by appinteractive**
For some words we need singular and plural. Therefore we can use the build in pluralization filter. But on thing is to be considered: Lokalize.io does support ICU Pluralization for very good reasons. We need to take a look how to use plurals the best way in both applications so the translates and the codes can use it without headaches.

~~- [ ] create ICU helper~~

OR

~~- [ ] switch from vuex-i18n to vue-i18n~~

### CODE REVIEW

**Comment by appinteractive** [comment]
We need therefore to create a translation helper to use IOC strings.

**Comment by roschaefer** [comment]
I hope the internationalization package already implements ICU?? :fearful:

**Comment by appinteractive** [comment]
Not in that version. None of the vue packages does that I know of. Vue-i18n will in the Next Version.

**Comment by appinteractive** [comment]
@roschaefer can be merged

**Comment by roschaefer** [comment]
@appinteractive why the heck are we still seeing the WIP check pending? Can we get rid of that service, too? The title of this PR apparently never had `[WIP]` in the name, now the service complains about it.

**Pull request merged**
