### PR TITLE
[WIP] 212 change password

### LINKED ISSUE #212: Change password
**Is your feature request related to a problem? Please describe.**
```gherkin
Feature: Change password
  As a user
  I want to change my password in my settings
  Because this is a basic security feature, e.g. if I exposed my password by accident
```

**Describe the solution you'd like**
This settings page on `/settings/security` should have a three fields `old password`, `new password` and `passwordConfirmation`, if they both match I should be able to change my password:

https://nitro-master.human-connection.org/settings/security

screenshot 34

### PR DESCRIPTION
**Pull request by roschaefer**
close #212

### CODE REVIEW

**Comment by mattwr18** [comment]
Screenshot at 2019-03-13 18:29:00

It looks good, and I notice that the backend branch has already been merged. 
Also, I notice that you have already written component tests! great!!
Maybe add some cypress tests and get this merged?

**Comment by mattwr18** [comment]
`Also, I notice that you have already written component tests! great!!`

I hadn't noticed that the component tests/implementation are still ongoing... probably shoulda noticed the `[WIP]`, but anyways great start!!

**Comment by roschaefer** [comment]
@mattwr18 we could continue on here. Just mark the tests regarding cross-validation of input fields as `it.skip(...)`. They are blocked by changes in the styleguide.

Regarding cypress tests: I would make an exception here. I think change password is *such* a common feature that we don't need to have it documented with a cucumber test.

**Comment by mattwr18** [comment]
And login is not @roschaefer?
or you don't think we should have a test for that either?

**Comment by roschaefer** [comment]
You mean because there is already a cypress test for login? 

This test is from a time when we did neither have backend nor frontend tests. :moyai: 

Writing a cypress test is a tradeoff: It gives extra confidence and documents behaviour from the point-of-view of the user. If you want to create a cypress test, go for it. I would also accept a PR that has a couple of component tests that assert the behaviour when the promise resolves or gets rejected.

**Comment by roschaefer** [comment]
closed in favour of https://github.com/Human-Connection/Human-Connection/pull/233

**Pull request closed without merging**
